package net.latinus.senescyt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:19:48.385-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://latinus.net/senescyt", name = "consultaTituloPortType")
@XmlSeeAlso({net.latinus.senescyt.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ConsultaTituloPortType {

    @WebResult(name = "titulos", targetNamespace = "http://latinus.net/senescyt/types", partName = "return")
    @WebMethod
    public net.latinus.senescyt.types.Titulos consultaTitulo(
        @WebParam(partName = "cedula", name = "cedula", targetNamespace = "http://latinus.net/senescyt/types")
        java.lang.String cedula
    ) throws ConsultaTituloFault;

    @WebResult(name = "titulos", targetNamespace = "http://latinus.net/senescyt/types", partName = "return")
    @WebMethod
    public net.latinus.senescyt.types.Titulos putTitulo(
        @WebParam(partName = "put_titulos", name = "put_titulos", targetNamespace = "http://latinus.net/senescyt/types")
        net.latinus.senescyt.types.PutTitulos putTitulos
    ) throws PutTituloFault;
}
