package net.latinus.senescyt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:19:48.399-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "consultaTituloPortType", 
                  wsdlLocation = "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_senescyt.wsdl",
                  targetNamespace = "http://latinus.net/senescyt") 
public class ConsultaTituloPortType_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://latinus.net/senescyt", "consultaTituloPortType");
    public final static QName ConsultaTituloPortTypePort = new QName("http://latinus.net/senescyt", "consultaTituloPortTypePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_senescyt.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaTituloPortType_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_senescyt.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaTituloPortType_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaTituloPortType_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaTituloPortType_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaTituloPortType_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaTituloPortType_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaTituloPortType_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaTituloPortType
     */
    @WebEndpoint(name = "consultaTituloPortTypePort")
    public ConsultaTituloPortType getConsultaTituloPortTypePort() {
        return super.getPort(ConsultaTituloPortTypePort, ConsultaTituloPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaTituloPortType
     */
    @WebEndpoint(name = "consultaTituloPortTypePort")
    public ConsultaTituloPortType getConsultaTituloPortTypePort(WebServiceFeature... features) {
        return super.getPort(ConsultaTituloPortTypePort, ConsultaTituloPortType.class, features);
    }

}
