
package net.latinus.senescyt;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:19:48.353-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "senescyt_fault", targetNamespace = "http://latinus.net/senescyt/types")
public class ConsultaTituloFault extends Exception {
    
    private net.latinus.senescyt.types.SenescytFault senescytFault;

    public ConsultaTituloFault() {
        super();
    }
    
    public ConsultaTituloFault(String message) {
        super(message);
    }
    
    public ConsultaTituloFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConsultaTituloFault(String message, net.latinus.senescyt.types.SenescytFault senescytFault) {
        super(message);
        this.senescytFault = senescytFault;
    }

    public ConsultaTituloFault(String message, net.latinus.senescyt.types.SenescytFault senescytFault, Throwable cause) {
        super(message, cause);
        this.senescytFault = senescytFault;
    }

    public net.latinus.senescyt.types.SenescytFault getFaultInfo() {
        return this.senescytFault;
    }
}
