//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.03 at 11:28:33 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sei.dinardap.info.com/")
package com.info.dinardap.sei.xsd;
