package net.latinus.wsdinardap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import ec.gob.dinardap.registrocivilservice.RegistroCivilService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T10:26:01.091-05:00
 * Generated source version: 2.7.6
 * 
 */
//@WebServiceClient(name = "civil_direlEctoralPortType", 
//                  wsdlLocation = "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_civil.wsdl",
//                  targetNamespace = "http://latinus.net/wsDinardap")
@WebServiceClient(name = "CivilDirelEctoralPortType", 
wsdlLocation = "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_civil.wsdl",
targetNamespace = "http://latinus.net/wsDinardap")
public class CivilDirelEctoralPortType extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://latinus.net/wsDinardap", "civil_direlEctoralPortType");
    public final static QName RegistroCivilServicePort = new QName("http://latinus.net/wsDinardap", "RegistroCivilServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_civil.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CivilDirelEctoralPortType.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_civil.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CivilDirelEctoralPortType(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CivilDirelEctoralPortType(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CivilDirelEctoralPortType() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CivilDirelEctoralPortType(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CivilDirelEctoralPortType(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CivilDirelEctoralPortType(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegistroCivilService
     */
    @WebEndpoint(name = "RegistroCivilServicePort")
    public RegistroCivilService getRegistroCivilServicePort() {
        return super.getPort(RegistroCivilServicePort, RegistroCivilService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistroCivilService
     */
    @WebEndpoint(name = "RegistroCivilServicePort")
    public RegistroCivilService getRegistroCivilServicePort(WebServiceFeature... features) {
        return super.getPort(RegistroCivilServicePort, RegistroCivilService.class, features);
    }

}
