package net.latinus.wsdinardap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:34:03.229-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "CNE_direlEctoral", 
                  wsdlLocation = "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_cne.wsdl",
                  targetNamespace = "http://latinus.net/wsDinardap") 
public class CNEDirelEctoral extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://latinus.net/wsDinardap", "CNE_direlEctoral");
    public final static QName CNEDirelEctoralPort = new QName("http://latinus.net/wsDinardap", "CNE_direlEctoralPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_cne.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CNEDirelEctoral.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/aromero/Middleware/Workspaces/fuse-workspace/POC-DINARDAP/dinardap/wsdl/ws_cne.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CNEDirelEctoral(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CNEDirelEctoral(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CNEDirelEctoral() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CNEDirelEctoral(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CNEDirelEctoral(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CNEDirelEctoral(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CNEDirelEctoralPortType
     */
    @WebEndpoint(name = "CNE_direlEctoralPort")
    public CNEDirelEctoralPortType getCNEDirelEctoralPort() {
        return super.getPort(CNEDirelEctoralPort, CNEDirelEctoralPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CNEDirelEctoralPortType
     */
    @WebEndpoint(name = "CNE_direlEctoralPort")
    public CNEDirelEctoralPortType getCNEDirelEctoralPort(WebServiceFeature... features) {
        return super.getPort(CNEDirelEctoralPort, CNEDirelEctoralPortType.class, features);
    }

}
