package net.latinus.wsdinardap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:34:03.214-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://latinus.net/wsDinardap", name = "CNE_direlEctoralPortType")
@XmlSeeAlso({net.latinus.wsdinardap.types.ObjectFactory.class})
public interface CNEDirelEctoralPortType {

    @RequestWrapper(localName = "consulta_cedula", targetNamespace = "http://latinus.net/wsDinardap/types", className = "net.latinus.wsdinardap.types.ConsultaCedula")
    @WebMethod(operationName = "consulta_cedula")
    @ResponseWrapper(localName = "cne", targetNamespace = "http://latinus.net/wsDinardap/types", className = "net.latinus.wsdinardap.types.Cne")
    public void consultaCedula(
        @WebParam(name = "i_cedula", targetNamespace = "")
        java.lang.String iCedula,
        @WebParam(name = "i_usuario", targetNamespace = "")
        java.lang.String iUsuario,
        @WebParam(name = "i_clave", targetNamespace = "")
        java.lang.String iClave,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "etiqueta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> etiqueta,
        @WebParam(mode = WebParam.Mode.OUT, name = "provincia", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> provincia,
        @WebParam(mode = WebParam.Mode.OUT, name = "canton", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> canton,
        @WebParam(mode = WebParam.Mode.OUT, name = "parroquia", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> parroquia,
        @WebParam(mode = WebParam.Mode.OUT, name = "recinto", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> recinto,
        @WebParam(mode = WebParam.Mode.OUT, name = "cedula", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> cedula,
        @WebParam(mode = WebParam.Mode.OUT, name = "nombre", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> nombre,
        @WebParam(mode = WebParam.Mode.OUT, name = "fecha", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> fecha,
        @WebParam(mode = WebParam.Mode.OUT, name = "sufrago", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> sufrago,
        @WebParam(mode = WebParam.Mode.OUT, name = "multa", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Double> multa,
        @WebParam(mode = WebParam.Mode.OUT, name = "partido", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> partido,
        @WebParam(mode = WebParam.Mode.OUT, name = "tipo", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> tipo,
        @WebParam(mode = WebParam.Mode.OUT, name = "certificado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> certificado
    ) throws ConsultaCedulaFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cne", targetNamespace = "http://latinus.net/wsDinardap/types", partName = "put_cne")
    @WebMethod(operationName = "put_cedula")
    public net.latinus.wsdinardap.types.Cne putCedula(
        @WebParam(partName = "put_cne", name = "put_cne", targetNamespace = "http://latinus.net/wsDinardap/types")
        net.latinus.wsdinardap.types.PutCne putCne
    ) throws PutCedulaFault;
}
