
package net.latinus.wsdinardap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:34:03.179-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "cne", targetNamespace = "http://latinus.net/wsDinardap/types")
public class ConsultaCedulaFault extends Exception {
    
    private net.latinus.wsdinardap.types.Cne cne;

    public ConsultaCedulaFault() {
        super();
    }
    
    public ConsultaCedulaFault(String message) {
        super(message);
    }
    
    public ConsultaCedulaFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConsultaCedulaFault(String message, net.latinus.wsdinardap.types.Cne cne) {
        super(message);
        this.cne = cne;
    }

    public ConsultaCedulaFault(String message, net.latinus.wsdinardap.types.Cne cne, Throwable cause) {
        super(message, cause);
        this.cne = cne;
    }

    public net.latinus.wsdinardap.types.Cne getFaultInfo() {
        return this.cne;
    }
}
