
package net.latinus.wsdinardap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T15:34:03.208-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "put_cne", targetNamespace = "http://latinus.net/wsDinardap/types")
public class PutCedulaFault extends Exception {
    
    private net.latinus.wsdinardap.types.PutCne putCne;

    public PutCedulaFault() {
        super();
    }
    
    public PutCedulaFault(String message) {
        super(message);
    }
    
    public PutCedulaFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PutCedulaFault(String message, net.latinus.wsdinardap.types.PutCne putCne) {
        super(message);
        this.putCne = putCne;
    }

    public PutCedulaFault(String message, net.latinus.wsdinardap.types.PutCne putCne, Throwable cause) {
        super(message, cause);
        this.putCne = putCne;
    }

    public net.latinus.wsdinardap.types.PutCne getFaultInfo() {
        return this.putCne;
    }
}
