
package ec.gob.dinardap.registrocivilservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T10:26:01.072-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "ceduladosFault", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/")
public class GetDatosRegistroCivilFaultMsg extends Exception {
    
    private ec.gob.dinardap.registrocivilservice.CeduladosFault ceduladosFault;

    public GetDatosRegistroCivilFaultMsg() {
        super();
    }
    
    public GetDatosRegistroCivilFaultMsg(String message) {
        super(message);
    }
    
    public GetDatosRegistroCivilFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public GetDatosRegistroCivilFaultMsg(String message, ec.gob.dinardap.registrocivilservice.CeduladosFault ceduladosFault) {
        super(message);
        this.ceduladosFault = ceduladosFault;
    }

    public GetDatosRegistroCivilFaultMsg(String message, ec.gob.dinardap.registrocivilservice.CeduladosFault ceduladosFault, Throwable cause) {
        super(message, cause);
        this.ceduladosFault = ceduladosFault;
    }

    public ec.gob.dinardap.registrocivilservice.CeduladosFault getFaultInfo() {
        return this.ceduladosFault;
    }
}
