
package ec.gob.dinardap.registrocivilservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T10:26:01.050-05:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "put_ceduladosFault", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/")
public class PutDatosRegistroCivilFaultMsg extends Exception {
    
    private ec.gob.dinardap.registrocivilservice.PutCeduladosFault putCeduladosFault;

    public PutDatosRegistroCivilFaultMsg() {
        super();
    }
    
    public PutDatosRegistroCivilFaultMsg(String message) {
        super(message);
    }
    
    public PutDatosRegistroCivilFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PutDatosRegistroCivilFaultMsg(String message, ec.gob.dinardap.registrocivilservice.PutCeduladosFault putCeduladosFault) {
        super(message);
        this.putCeduladosFault = putCeduladosFault;
    }

    public PutDatosRegistroCivilFaultMsg(String message, ec.gob.dinardap.registrocivilservice.PutCeduladosFault putCeduladosFault, Throwable cause) {
        super(message, cause);
        this.putCeduladosFault = putCeduladosFault;
    }

    public ec.gob.dinardap.registrocivilservice.PutCeduladosFault getFaultInfo() {
        return this.putCeduladosFault;
    }
}
