package ec.gob.dinardap.registrocivilservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-03T10:26:01.078-05:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/", name = "RegistroCivilService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RegistroCivilService {

    @WebResult(name = "cedulados", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/", partName = "put_cedulados")
    @WebMethod(action = "http://www.dinardap.gob.ec/RegistroCivilService/putDatosRegistroCivil")
    public Cedulados putDatosRegistroCivil(
        @WebParam(partName = "put_cedulados", name = "put_cedulados", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/")
        PutCedulados putCedulados
    ) throws PutDatosRegistroCivilFaultMsg;

    @WebResult(name = "cedulados", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/", partName = "cedulados")
    @WebMethod(action = "http://www.dinardap.gob.ec/RegistroCivilService/getDatosRegistroCivil")
    public Cedulados getDatosRegistroCivil(
        @WebParam(partName = "cedula", name = "cedula", targetNamespace = "http://www.dinardap.gob.ec/RegistroCivilService/")
        Cedula cedula
    ) throws GetDatosRegistroCivilFaultMsg;
}
